[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:staging"

[deploy]
startCommand = "npx serve -s dist -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "staging" 